Repository nextcloud/guests, pull requests merged in 2019-11, with the labels that each got.

#206 Do not create an app instance manually from routes either
  appinfo/routes.php
Labels: 3. to review, bug

#207 Use the event dispatcher interface
  lib/UserBackend.php
  tests/unit/UserBackendTest.php
Labels: 3. to review, bug

#209 Use typed password events
  .travis.yml
  appinfo/info.xml
  lib/GuestManager.php
  lib/UserBackend.php
  package-lock.json
  package.json
  tests/unit/UserBackendTest.php
Labels: 4. to release, enhancement

#153 Update app to fit 18 new Sharing sidebar
  .babelrc
  .drone.yml
  .eslintrc.js
  .gitignore
  .stylelintrc.js
  Makefile
  appinfo/info.xml
  babel.config.js
  css/app.css
  css/personal.css
  lib/AppInfo/Application.php
  lib/Controller/SettingsController.php
  lib/GuestManager.php
  lib/RestrictionManager.php
  package-lock.json
  package.json
  src/GuestDetails.vue
  src/GuestForm.vue
  src/GuestList.vue
  src/GuestSettings.vue
  src/LanguageSelect.vue
  src/ShareDialogPlugin.js
  src/components/GuestDetails.vue
  src/components/GuestList.vue
  src/components/LanguageSelect.vue
  src/index.js
  src/settings.js
  src/views/GuestForm.vue
  src/views/GuestSettings.vue
  webpack.common.js
Labels: 4. to release, enhancement, high, javascript
