Repository nextcloud/guests, pull requests merged in 2019-12, with the labels that each got.

#208 Import guest user data into system user account at first login
  .travis.yml
  lib/AppInfo/Application.php
  lib/Hooks.php
  lib/Notifications/Notifier.php
  tests/unit/AppWhitelistTest.php
  tests/unit/GroupBackendTest.php
  tests/unit/GuestManagerTest.php
  tests/unit/UserBackendTest.php
Labels: 4. to release

#221 Do not load the removed app.css file
  lib/AppInfo/Application.php
Labels: 3. to review, regression

#224 documented guest conversion settings and prerequisites
  README.md
Labels: 4. to release, enhancement
