Repository nextcloud/guests, pull requests merged in 2020-07, with the labels that each got.

#418 Use webpack global config, github actions & update deps
  .eslintrc.js
  .github/workflows/lint.yml
  .github/workflows/node.yml
  .github/workflows/phpunit.yml
  .gitignore
  .php_cs.dist
  .travis.yml
  appinfo/info.xml
  composer.json
  composer.lock
  lib/AppConfigOverwrite.php
  lib/AppInfo/Application.php
  lib/AppWhitelist.php
  lib/Command/ListCommand.php
  lib/Config.php
  lib/Controller/APIController.php
  lib/Controller/SettingsController.php
  lib/Controller/UsersController.php
  lib/GroupBackend.php
  lib/GuestManager.php
  lib/Hooks.php
  lib/Listener/ShareAutoAcceptListener.php
  lib/Mail.php
  lib/Migration/Version1Date20180615130406.php
  lib/Notifications/Notifier.php
  lib/RestrictionManager.php
  lib/Storage/DirMask.php
  lib/Storage/DirMaskCache.php
  lib/Storage/ReadOnlyJail.php
  lib/UserBackend.php
  package-lock.json
  package.json
  phpunit.xml
  src/components/GroupSelect.vue
  src/components/GuestDetails.vue
  src/components/LanguageSelect.vue
  src/main.js
  src/views/GuestForm.vue
  stylelint.config.js
  templates/settings/admin.php
  tests/integration/features/bootstrap/GuestsContext.php
  tests/unit/AppConfigOverwriteTest.php
  tests/unit/AppWhitelistTest.php
  tests/unit/GroupBackendTest.php
  tests/unit/GuestManagerTest.php
  tests/unit/Storage/DirMaskTest.php
  tests/unit/UserBackendTest.php
  webpack.common.js
  webpack.dev.js
  webpack.js
  webpack.prod.js
Labels: 3. to review, dependencies, enhancement

#420 Test against master
  .github/workflows/phpunit.yml
Labels: 3. to review, enhancement

#421 Allow to obtain the real user id
  lib/UserBackend.php
Labels: 4. to release, bug
