Repository nextcloud/guests, pull requests merged in 2020-02, with the labels that each got.

#265 More github actions
  .drone.yml
  .github/workflows/lint.yml
  .github/workflows/nodejs.yml
  composer.json
Labels: 3. to review

#264 On firstlogin filetransfer
  appinfo/info.xml
  lib/Hooks.php
Labels: 4. to release, enhancement

#272 Guest users always auto accept shares
  lib/AppInfo/Application.php
  lib/Listener/ShareAutoAcceptListener.php
Labels: 3. to review

#282 Fix untranslated string
  src/index.js
Labels: bug
