Repository nextcloud/guests, pull requests merged in 2020-03, with the labels that each got.

#307 updated readme according to release 1.4.2
  README.md
Labels: 3. to review, pending documentation

#309 Add OCS API
  appinfo/routes.php
  lib/Controller/APIController.php
  lib/Controller/SettingsController.php
  lib/Controller/UsersController.php
  src/components/GuestDetails.vue
  src/components/GuestList.vue
  src/components/LanguageSelect.vue
  src/views/GuestForm.vue
Labels: 3. to review, enhancement

#320 Delay call to canCreateGuests when checking for loaded scripts
  lib/AppInfo/Application.php
Labels: 3. to review, bug
