Repository nextcloud/guests, pull requests merged in 2021-08, with the labels that each got.

#701 Add fixup
  .github/workflows/fixup.yml
Labels: enhancement, 4. to release

#702 Move to IBootstrap
  appinfo/app.php
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Listener/LoadAdditionalScriptsListener.php
Labels: 2. developing

#724 Force-load theme at the right moment
  lib/AppInfo/Application.php
Labels: bug, regression, 3. to review
