Repository nextcloud/guests, pull requests merged in 2021-11, with the labels that each got.

#785 Simplify makefile and fix bundles
  Makefile
  package-lock.json
  package.json
  src/views/GuestForm.vue
Labels: 3. to review

#786 Updating appstore-build-publish.yml workflow from template
  .github/workflows/appstore-build-publish.yml
Labels: dependencies

#799 Add return value when successfully creating a user through occ
  lib/Command/AddCommand.php
  lib/Command/ListCommand.php
Labels: bug, 3. to review
