Repository nextcloud/guests, pull requests merged in 2022-04, with the labels that each got.

#840 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#863 Updating node.yml workflow from template
  .github/workflows/node.yml
Labels: dependencies

#879 Configs update before 23+24 release
  .php-cs-fixer.dist.php
  composer.lock
  package-lock.json
  package.json
  src/components/GroupSelect.vue
  src/components/LanguageSelect.vue
  src/views/GuestForm.vue
  stylelint.config.js
Labels: enhancement, design, technical debt, 4. to release

#880 Bump workflows + 24 release
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/lint-eslint.yml
  .github/workflows/lint-info-xml.yml
  .github/workflows/lint-php-cs.yml
  .github/workflows/lint-php.yml
  .github/workflows/lint-stylelint.yml
  .github/workflows/lint.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
  .github/workflows/phpunit.yml
  .gitignore
  CHANGELOG.md
  appinfo/info.xml
  composer.json
  composer.lock
  lib/Command/AddCommand.php
  package-lock.json
  package.json
Labels: enhancement, 4. to release

#881 Update screenshots
  screenshots/dialog.png
  screenshots/dropdown.png
Labels: 3. to review
