Repository nextcloud/guests, pull requests merged in 2022-10, with the labels that each got.

#946 Fix allowlist button handler
  src/views/GuestSettings.vue
Labels: 3. to review

#953 Updating lint-php-cs.yml workflow from template
  .github/workflows/lint-php-cs.yml
Labels: dependencies

#951 Updating lint-php.yml workflow from template
  .github/workflows/lint-php.yml
Labels: dependencies

#952 Updating lint-stylelint.yml workflow from template
  .github/workflows/lint-stylelint.yml
Labels: dependencies

#959 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#958 Updating psalm.yml workflow from template
  .github/workflows/psalm.yml
Labels: dependencies

#957 Updating phpunit-sqlite.yml workflow from template
  .github/workflows/phpunit-sqlite.yml
Labels: dependencies

#956 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#955 Updating lint-eslint.yml workflow from template
  .github/workflows/lint-eslint.yml
Labels: dependencies

#945 Remove unused dependency deep-equal
  package-lock.json
  package.json
Labels: 3. to review

#961 Updating phpunit-pgsql.yml workflow from template
  .github/workflows/phpunit-pgsql.yml
Labels: dependencies

#933 Adjust testing matrix for Nextcloud 25 on master
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/psalm.yml
Labels: 4. to release
