Repository nextcloud/guests, pull requests merged in 2024-07, with the labels that each got.

#1194 feat: Implement IPasswordHashBackend
  appinfo/info.xml
  composer.lock
  lib/UserBackend.php
Labels: enhancement, 3. to review

#1173 feat: Add transfer endpoint
  appinfo/routes.php
  img/account-arrow-right.svg
  lib/BackgroundJob/TransferJob.php
  lib/Controller/UsersController.php
  lib/Db/Transfer.php
  lib/Db/TransferMapper.php
  lib/GuestManager.php
  lib/Hooks.php
  lib/Migration/Version4000Date20240619221613.php
  lib/Notifications/Notifier.php
  lib/TransferService.php
Labels: enhancement, 3. to review

#1174 feat: Allow transferring guests to full accounts
  .eslintrc.cjs
  appinfo/routes.php
  lib/AppInfo/Application.php
  lib/Listener/BeforeUserManagementRenderedListener.php
  package-lock.json
  package.json
  src/components/GuestDetails.vue
  src/components/TransferGuestDialog.vue
  src/env.d.ts
  src/services/logger.ts
  src/shims.d.ts
  src/types.ts
  src/users.ts
  tests/stub.php
  vite.config.ts
Labels: enhancement, 3. to review

#1155 Updating dependabot-approve-merge.yml workflow from template
  .github/workflows/dependabot-approve-merge.yml
Labels: dependencies

#1207 fix(README): Fix guest specific behavior section links
  README.md
Labels: bug, 3. to review
