Repository nextcloud/guests, pull requests merged in 2024-06, with the labels that each got.

#1133 Updating phpunit-mysql.yml workflow from template
  .github/workflows/phpunit-mysql.yml
Labels: dependencies

#1170 Fix tests
  tests/stub.php
Labels: 3. to review

#1169 feat: Upgrade dependencies and migrate to nc/vue v8
  package-lock.json
  package.json
  src/components/GroupSelect.vue
  src/components/GuestList.vue
  src/components/LanguageSelect.vue
  src/views/GuestForm.vue
  src/views/GuestSettings.vue
Labels: enhancement, dependencies, 3. to review

#1151 Add 'direct' GET param to invite email 'view share' link
  lib/Mail.php
Labels: enhancement, 3. to review

#1172 chore: Move to vite
  .eslintrc.cjs
  babel.config.js
  lib/Listener/LoadAdditionalScriptsListener.php
  lib/Settings/Admin.php
  package-lock.json
  package.json
  stylelint.config.js
  templates/settings/admin.php
  tsconfig.json
  vite.config.ts
  webpack.js
Labels: 3. to review

#1154 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1178 fix(GuestForm): allow to create a guest without name more than once
  src/views/GuestForm.vue
Labels: bug, 3. to review

#1181 chore: add changelog for 2.4.0 .. 3.0.1
  CHANGELOG.md
Labels: technical debt, backport-request, 3. to review

#1183 release: v2.5.2
  CHANGELOG.md
  appinfo/info.xml
Labels: technical debt, 3. to review

#1184 [stable28] chore: add changelog for 2.4.0 .. 3.0.1
  CHANGELOG.md
Labels: technical debt, 3. to review

#1189 fix(Sharing): Do not create new share in guest app
  src/services/logger.ts
  src/views/GuestForm.vue
Labels: backport-request
