Repository nextcloud/guests, pull requests merged in 2024-08, with the labels that each got.

#1227 Add missing div id (fixes CSS lack)
  src/components/GuestList.vue
Labels: bug, design, 3. to review, papercut

#1229 refactor: Migrate from deprecated `ILogger` interface to PSR-3 logger
  lib/AppWhitelist.php
  lib/Listener/ShareAutoAcceptListener.php
  lib/Mail.php
  tests/stub.php
  tests/unit/AppWhitelistTest.php
Labels: technical debt, 3. to review

#1228 Replace "transfer" notion with "convert" notion
  lib/Notifications/Notifier.php
  src/components/TransferGuestDialog.vue
  src/users.ts
Labels: enhancement, design, 3. to review, papercut
