Repository nextcloud/guests, pull requests merged in 2025-08, with the labels that each got.

#1367 fix: remove constructor overwrite from AppConfigOverwrite
  lib/AppConfigOverwrite.php
  lib/RestrictionManager.php
Labels: 3. to review

#1370 feat: add repair step to ensure guests haven't changed their email
  appinfo/info.xml
  lib/Repair/ResetEmails.php
Labels: 3. to review

#1372 chore: 4.4.0
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1374 fix: ensure repair email is a string
  lib/Repair/ResetEmails.php
Labels: bug, 3. to review

#1375 chore: update composer to fix psalm
  composer.json
  composer.lock
  lib/AppConfigOverwrite.php
  lib/AppInfo/Application.php
  lib/AppWhitelist.php
  lib/Config.php
  lib/FilteredSettingsManager.php
  lib/GroupBackend.php
  lib/GuestManager.php
  lib/Listener/BeforeUserManagementRenderedListener.php
  lib/Listener/LoadAdditionalScriptsListener.php
  lib/Mail.php
  lib/Migration/OwncloudGuestsMigration.php
  lib/Repair/ResetEmails.php
  lib/UserBackend.php
  psalm.xml
  tests/psalm-baseline.xml
  tests/unit/Controller/UsersControllerTest.php
Labels: 2. developing

#1357 fix: accept INavigationManager instead of NavigationManager in Filter…
  composer.json
  lib/FilteredNavigationManager.php
  lib/Storage/DirMask.php
  tests/psalm-baseline.xml
  tests/stub.php
Labels: feedback-requested

#1380 feat: add guests through the contacts menu
  lib/Listener/BeforeTemplateRenderedListener.php
  src/contactsmenu.ts
  vite.config.ts
Labels: enhancement, 3. to review

#1382 chore: 4.4.1
  CHANGELOG.md
  appinfo/info.xml
  package-lock.json
  package.json
Labels: 3. to review

#1388 build: update node and npm engines versions
  package.json
Labels: dependencies
