Repository nextcloud/guests, pull requests merged in 2025-02, with the labels that each got.

#1288 chore(CI): Updating pr-feedback.yml workflow from template
  .github/workflows/pr-feedback.yml
Labels: dependencies

#1298 ci: Update actions
  .github/workflows/dependabot-approve-merge.yml
  .github/workflows/phpunit-mysql.yml
  .github/workflows/phpunit-oci.yml
  .github/workflows/phpunit-pgsql.yml
  .github/workflows/phpunit-sqlite.yml
Labels: 3. to review

#1299 fix: settings save
  package-lock.json
  package.json
  src/views/GuestSettings.vue
Labels: bug, high, 3. to review

#1301 chore: 4.2.0 release
  CHANGELOG.md
  appinfo/info.xml
  package.json
Labels: 3. to review
